# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_remove_description_coursedescrip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
