# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_auto_20170225_0453'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('courseManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
